-- Product Backlog (Hybrid PM Step 3). WBS의 Work Package가 범위를 정하고, 그 범위를 실제로 구현하는
-- 실행 항목이 여기에 쌓인다.
--
-- 한 테이블에 Epic·Story·Bug·Task를 함께 둔다. RAID와 같은 이유다 — 제목·상태·담당자·우선순위 등
-- 대부분의 필드를 공유하고 한 화면에서 함께 읽히므로, 종류별 테이블은 CRUD를 네 벌로 늘리면서 얻는
-- 것이 없다. 계층은 parent_id 하나로 표현한다 (Epic → Story/Bug → Task).
--
-- Product Backlog는 "정렬된 목록"이지 계층 노드가 아니다(설계 §4.1). 그래서 WBS처럼 코드를 파생하거나
-- 트리를 조립하지 않고, 우선순위와 sort_order로 정렬만 한다.
CREATE TABLE backlog_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,

    -- 귀속 Work Package. NULL은 "미연결"이며 초안 상태로 허용한다(설계 §4.2: 미분류 Backlog).
    -- Sprint 투입 전에 채워져야 하고, 그 판정은 Step 4가 쓴다.
    --
    -- SET NULL 인 이유: CASCADE 면 WBS 항목을 지울 때 실행 기록이 조용히 사라진다. 실제로는
    -- BacklogService/WbsService가 그 전에 삭제를 거부하므로 여기까지 오지 않지만, 마지막 방어선이
    -- 데이터를 지우는 쪽이어서는 안 된다.
    wbs_item_id BIGINT,

    -- Epic → Story/Bug, Story/Bug → Task. 하위 항목은 상위의 귀속을 따른다(애플리케이션에서 강제).
    -- CASCADE 인 이유: Task는 Story의 실행 상세라 부모 없이 존재할 의미가 없다. 다만 서비스가
    -- 하위가 있는 항목의 삭제를 거부하므로, 이 연쇄는 실수로 실행되지 않는다.
    parent_id BIGINT,

    item_type VARCHAR(20) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    priority VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,

    -- 담당자는 프로젝트 구성원을 가리킨다. RAID 소유자와 같은 이유로 SET NULL —
    -- 구성원이 빠지면 항목은 남고 담당자만 비워져야 한다.
    assignee_member_id BIGINT,

    acceptance_criteria VARCHAR(2000),

    -- story_point 와 progress_weight 는 서로 다른 값이다(설계 §11.2). 포인트는 팀의 실행 추정이고,
    -- 가중치는 같은 Work Package 안에서의 진척 비중이다. 같은 단위로 합산하지 않는다.
    story_point INT,
    progress_weight INT,

    -- 보관(archive). 상태(status)와 직교한다 — 보관해도 마지막 상태는 그대로 남아야 하고,
    -- 상태를 한 칸 늘리면 Step 4의 Board 상태 전이에 "보관"이 섞여 든다.
    archived_at TIMESTAMP,

    sort_order INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_backlog_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_backlog_wbs_item FOREIGN KEY (wbs_item_id) REFERENCES wbs_items (id) ON DELETE SET NULL,
    CONSTRAINT fk_backlog_parent FOREIGN KEY (parent_id) REFERENCES backlog_items (id) ON DELETE CASCADE,
    CONSTRAINT fk_backlog_assignee FOREIGN KEY (assignee_member_id) REFERENCES project_members (id) ON DELETE SET NULL,
    CONSTRAINT ck_backlog_story_point CHECK (story_point IS NULL OR story_point >= 0),
    -- 가중치는 음수가 될 수 없다(설계 §11.3-5).
    CONSTRAINT ck_backlog_progress_weight CHECK (progress_weight IS NULL OR progress_weight >= 0)
);

CREATE INDEX idx_backlog_project ON backlog_items (project_id);
CREATE INDEX idx_backlog_wbs_item ON backlog_items (wbs_item_id);
CREATE INDEX idx_backlog_parent ON backlog_items (parent_id);
