-- Backlog 항목의 귀속(Work Package) 변경 이력 (Step 3 지시서 8항: 삭제·재귀속 시 변경 이력을 보존).
--
-- Step 2의 wbs_execution_mode_changes 와 같은 성격의 좁은 표다. 설계 §11.1의 일반 ChangeLog 는
-- Step 5에서 가중치·Baseline 이력과 함께 도입하며 두 표를 그때 흡수한다 — 지금 일반 표를 만들면
-- Step 5의 기능을 선행 구현하는 셈이다.
--
-- reason 은 사람이 적는 사유가 아니라 시스템이 정하는 코드다. 로그인이 없어 변경자는 기록할 수 없고,
-- 자유 입력 사유를 받을 화면도 없다. 대신 "왜 끊겼는지"는 코드로 구분한다 — 사용자가 옮긴 것과
-- WBS 삭제로 분리된 것은 나중에 완전히 다른 의미가 된다.
CREATE TABLE backlog_link_changes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    backlog_item_id BIGINT NOT NULL,
    -- 미연결(NULL) → 연결, 연결 → 미연결 모두 이력이므로 양쪽 다 NULL을 허용한다.
    previous_wbs_item_id BIGINT,
    new_wbs_item_id BIGINT,
    reason VARCHAR(30) NOT NULL,
    changed_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_backlog_link_change_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_backlog_link_change_item FOREIGN KEY (backlog_item_id) REFERENCES backlog_items (id) ON DELETE CASCADE
    -- previous/new WBS id에는 FK를 걸지 않는다. WBS 항목이 지워진 뒤에도 "그 항목에 붙어 있었다"는
    -- 사실이 남아야 하는데, FK를 걸면 그 순간 NULL이 되거나 삭제를 막게 된다.
);

CREATE INDEX idx_backlog_link_change_project ON backlog_link_changes (project_id);
CREATE INDEX idx_backlog_link_change_item ON backlog_link_changes (backlog_item_id);
