-- Sprint (Hybrid PM Step 4).
--
-- **팀 컬럼을 두지 않는다.** 단일 팀으로 운영하기로 결정했다(사용자 결정). 설계 §11.1의 Team은
-- Sprint와 추정의 팀 기준이고 Step 7의 팀별 속도 추세에 쓰이지만, 팀이 하나면 모든 Sprint가 같은
-- 팀의 것이라 컬럼이 언제나 같은 값을 갖는다.
--
-- 팀이 둘 이상 필요해지면: `teams` 테이블을 만들고 `sprints.team_id`를 추가한 뒤 기존 행을 기본 팀
-- 하나로 백필하면 된다. 그때까지는 "이 프로젝트의 Sprint는 한 팀의 것"이 전제이며, 그 전제가
-- 아래 '활성 Sprint는 프로젝트당 하나' 규칙의 근거다.
CREATE TABLE sprints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    goal VARCHAR(1000),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    -- PLANNED → ACTIVE → CLOSED. 되돌아가지 않는다 (종료된 Sprint의 결과는 이력이다).
    status VARCHAR(20) NOT NULL,
    closed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_sprints_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    -- 목록에서 구분할 수 없는 같은 이름의 Sprint 두 개를 막는다 (project_members 와 같은 이유).
    CONSTRAINT uq_sprints_name UNIQUE (project_id, name),
    CONSTRAINT ck_sprints_period CHECK (start_date <= end_date)
);

CREATE INDEX idx_sprints_project ON sprints (project_id);
