-- Sprint 배정과 그 결과 (Hybrid PM Step 4 지시서 8·9항).
--
-- 배정 자체가 이력이다. 제거는 행을 지우지 않고 removed_at 을 찍고, 종료 시에는 outcome 과
-- points_at_close 를 남긴다. 그래야 "원 Sprint에 미완료로 남기고 재배정한다"가 성립한다 —
-- 재배정이 과거 Sprint의 결과를 건드리면 안 된다.
--
-- **(sprint_id, backlog_item_id) 에 UNIQUE 를 걸지 않는다.** 설계 §11.3-4는 유일성을 권하지만,
-- 그러면 같은 Sprint에서 뺀 항목을 다시 넣을 때 기존 행을 되살려야 하고 "한 번 빠졌다"는 사실이
-- 사라진다. 지시서 8항이 배정과 제거를 모두 보존하라고 하므로 행을 쌓는 쪽을 골랐다.
-- 대신 **활성 배정(removed_at IS NULL)은 (sprint, item) 당 하나**이며, 이 제약은 애플리케이션에서
-- 지킨다 — 부분 유니크 인덱스는 PostgreSQL에는 있지만 H2에는 없어 양쪽에 같은 DDL을 쓸 수 없다.
CREATE TABLE sprint_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    sprint_id BIGINT NOT NULL,
    backlog_item_id BIGINT NOT NULL,

    added_at TIMESTAMP NOT NULL,
    -- NULL = 아직 이 Sprint에 들어 있음.
    removed_at TIMESTAMP,

    -- 추정값은 시점마다 다르다. 시작 시점과 종료 시점을 따로 찍어 두면 나중에 "계획보다
    -- 늘었나"를 설명할 수 있다. Story Point 자체는 backlog_items 에 있고 계속 바뀔 수 있다.
    points_at_start INT,
    points_at_close INT,

    -- Sprint 종료 시에 정해진다. 열려 있는 동안은 NULL.
    outcome VARCHAR(20),

    CONSTRAINT fk_sprint_items_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_sprint_items_sprint FOREIGN KEY (sprint_id) REFERENCES sprints (id) ON DELETE CASCADE,
    -- Backlog 항목이 지워지면 그 배정 기록도 가리킬 대상이 없다. 다만 서비스가 활성 배정이 있는
    -- 항목의 삭제를 거부하므로, 이 연쇄는 실수로 실행되지 않는다.
    CONSTRAINT fk_sprint_items_backlog FOREIGN KEY (backlog_item_id) REFERENCES backlog_items (id) ON DELETE CASCADE
);

CREATE INDEX idx_sprint_items_sprint ON sprint_items (sprint_id);
CREATE INDEX idx_sprint_items_backlog ON sprint_items (backlog_item_id);
CREATE INDEX idx_sprint_items_project ON sprint_items (project_id);
