-- Waterfall·Hybrid의 승인 체크포인트 (Hybrid PM Step 5-A, 설계 §6.3).
--
-- Waterfall 진척은 "승인된 체크포인트 가중치 합 / 전체 체크포인트 가중치 합"이다. 즉 이 표가
-- 그 분모다. 체크포인트가 없는 Waterfall Work Package는 분모가 0이므로 **산정 전**이 되며,
-- 0%로 단정하지 않는다.
--
-- approved_by 는 자유 입력 문자열이다. 로그인이 없어 계정을 가리킬 수 없지만, 승인은 "누가"가
-- 핵심인 행위라 비워 둘 수 없다. 계정이 생기면 그때 참조로 승격한다.
CREATE TABLE acceptance_checkpoints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    wbs_item_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    -- NULL은 균등(1)으로 본다. 체크포인트 셋에 아무 가중치도 넣지 않은 것은
    -- "셋이 같은 비중"이라는 정상적인 표현이다.
    weight INT,
    -- 완료 조건. 승인 판단의 근거를 적는 곳이며, 시스템이 내용을 검증하지는 않는다.
    completion_criteria VARCHAR(2000),
    approved BOOLEAN DEFAULT FALSE NOT NULL,
    approved_by VARCHAR(100),
    approved_at TIMESTAMP,
    sort_order INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_checkpoint_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_checkpoint_wbs_item FOREIGN KEY (wbs_item_id) REFERENCES wbs_items (id) ON DELETE CASCADE,
    CONSTRAINT ck_checkpoint_weight CHECK (weight IS NULL OR weight >= 0)
);

CREATE INDEX idx_checkpoint_project ON acceptance_checkpoints (project_id);
CREATE INDEX idx_checkpoint_wbs_item ON acceptance_checkpoints (wbs_item_id);
