-- 승인된 기준(Baseline) (Hybrid PM Step 5-A, 설계 §11.1).
--
-- **자동으로 만들지 않는다.** 사용자가 명시적으로 승인할 때만 생성된다 — 지시서가 "Baseline을 자동
-- 승인하거나 실제 프로젝트에 임의 생성하지 않는다"고 못 박고 있고, 승인되지 않은 기준선은
-- 계획 대비 비교의 근거가 되지 못한다.
--
-- 승인 시점의 범위·일정·가중치·완료 기준을 **복사해서** 보존한다. 참조로 두면 원본이 바뀌는 순간
-- "승인했던 계획"이 사라진다 — 그것이 Baseline이 존재하는 이유 전체다.
CREATE TABLE baselines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    -- 프로젝트 안에서 1부터 올라간다. 사람이 "2차 기준"이라고 부를 수 있는 번호다.
    version INT NOT NULL,
    -- 로그인이 없어 계정을 가리킬 수 없다. 승인은 "누가"가 핵심이라 자유 입력으로 받는다.
    approved_by VARCHAR(100) NOT NULL,
    approved_at TIMESTAMP NOT NULL,
    note VARCHAR(1000),

    CONSTRAINT fk_baseline_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT uq_baseline_version UNIQUE (project_id, version)
);

CREATE INDEX idx_baseline_project ON baselines (project_id);

-- 승인 시점의 각 WBS 항목. wbs_item_id 에 FK를 걸지 않는다 — 항목이 지워진 뒤에도 "그때 이런 범위를
-- 승인했다"는 사실이 남아야 하고, FK를 걸면 그 순간 NULL이 되거나 삭제를 막는다.
-- code·name 을 함께 복사하는 것도 같은 이유다(코드는 트리 위치에서 파생되므로 나중에 재현할 수 없다).
CREATE TABLE baseline_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    baseline_id BIGINT NOT NULL,
    wbs_item_id BIGINT NOT NULL,
    code VARCHAR(100),
    name VARCHAR(255) NOT NULL,
    node_type VARCHAR(20) NOT NULL,
    execution_mode VARCHAR(20),
    start_date DATE,
    end_date DATE,
    weight INT,
    completion_criteria VARCHAR(2000),

    CONSTRAINT fk_baseline_item_baseline FOREIGN KEY (baseline_id) REFERENCES baselines (id) ON DELETE CASCADE
);

CREATE INDEX idx_baseline_item_baseline ON baseline_items (baseline_id);
