-- 일반 변경 이력 (Hybrid PM Step 5-A, 설계 §11.1의 ChangeLog).
--
-- Step 2와 Step 3에서 각각 좁은 이력 표를 만들며 "일반 ChangeLog는 Step 5에서 도입하고 이 표를
-- 흡수한다"고 적어 두었다. 이제 그렇게 한다 — 가중치 변경 이력까지 네 번째 표를 만들 이유가 없다.
--
-- 대상은 FK 없이 (entity_type, entity_id)로 가리킨다. 지워진 항목에 대한 변경 기록도 남아야 하며,
-- 그것이 "가중치와 범위 변경 이력을 보존하여 분모 변경으로 인한 진척 변화를 설명한다"(설계 §6.1)의
-- 전제다.
CREATE TABLE change_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id BIGINT NOT NULL,
    -- 무엇이 바뀌었는지. 한 필드 단위로 남긴다 — 엔티티 전체를 직렬화해 두면 무엇이 달라졌는지
    -- 읽는 쪽이 다시 비교해야 한다.
    field VARCHAR(40) NOT NULL,
    before_value VARCHAR(500),
    after_value VARCHAR(500),
    -- 시스템이 정하는 사유 코드. 사용자가 적는 자유 사유는 받을 화면이 없다.
    reason VARCHAR(40) NOT NULL,
    changed_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_change_log_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE
);

CREATE INDEX idx_change_log_project ON change_logs (project_id);
CREATE INDEX idx_change_log_entity ON change_logs (entity_type, entity_id);

-- 기존 두 표의 내용을 옮긴다. 값을 잃지 않고 흡수하는 것이 이 마이그레이션의 요점이다.
INSERT INTO change_logs (project_id, entity_type, entity_id, field, before_value, after_value, reason, changed_at)
SELECT project_id, 'WBS_ITEM', wbs_item_id, 'executionMode', previous_mode, new_mode, 'REASSIGNED', changed_at
  FROM wbs_execution_mode_changes;

INSERT INTO change_logs (project_id, entity_type, entity_id, field, before_value, after_value, reason, changed_at)
SELECT project_id, 'BACKLOG_ITEM', backlog_item_id, 'wbsItemId',
       CAST(previous_wbs_item_id AS VARCHAR(500)), CAST(new_wbs_item_id AS VARCHAR(500)),
       reason, changed_at
  FROM backlog_link_changes;

DROP TABLE wbs_execution_mode_changes;
DROP TABLE backlog_link_changes;
