-- 진척 보고 스냅샷 (Hybrid PM Step 5-C, 설계 §6.5 "과거 보고").
--
-- 진척은 저장하지 않고 매번 계산한다(설계 §11.3-8: 저장된 집계값은 재생성 가능한 캐시). 그런데
-- **과거 보고는 재현할 수 없다** — 그때의 범위·가중치·정책이 지금과 다르기 때문이다. 그래서 보고한
-- 시점의 결과만 따로 찍어 둔다.
--
-- metrics 는 JSON 문자열이다. 프로젝트 수준 집계만 담으므로 길이가 예측 가능하고, 컬럼을 지표마다
-- 늘리면 지표가 하나 생길 때 마이그레이션이 필요해진다. 항목별 상세는 담지 않는다 — 최소 스냅샷의
-- 범위를 넘고, 큰 프로젝트에서 크기가 폭발한다.
CREATE TABLE progress_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    -- 보고일. 서버가 정한다 (지연 판정의 referenceDate와 같은 이유).
    as_of DATE NOT NULL,
    -- 어느 기준선과 비교한 보고인가. Baseline이 없으면 NULL이고, 그때 계획 진척은 미산정이다.
    baseline_id BIGINT,
    -- 그때의 범위 규모. 별도의 "범위 버전" 엔티티는 두지 않았다 — 승인된 범위는 Baseline이고,
    -- 현재 범위는 이 두 값으로 설명된다.
    scope_item_count INT NOT NULL,
    scope_weight_total INT,
    metrics VARCHAR(4000) NOT NULL,
    note VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_snapshot_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    -- Baseline이 지워지면 스냅샷은 남고 참조만 비워야 한다. 보고했던 사실 자체는 사라지면 안 된다.
    CONSTRAINT fk_snapshot_baseline FOREIGN KEY (baseline_id) REFERENCES baselines (id) ON DELETE SET NULL
);

CREATE INDEX idx_snapshot_project ON progress_snapshots (project_id);
