-- RAID 항목의 복수 연결 (Hybrid PM Step 6-C, 설계 §9의 RaidLink).
--
-- 지금까지 RAID는 WBS 하나에만 붙을 수 있었다(raid_items.wbs_item_id). 설계는 "하나의 RAID 항목을
-- 여러 WBS·Sprint·Backlog에 연결"하라고 한다 — 같은 위험이 여러 Story에 영향을 주더라도 원본은
-- 하나로 관리해야 하기 때문이다.
--
-- target_type/target_id 로 가리키고 FK는 걸지 않는다. 세 종류의 대상을 한 컬럼으로 가리키므로
-- FK를 걸 수 없고, 애플리케이션이 대상 존재와 프로젝트 일치를 검증한다(설계 §11.3-7).
CREATE TABLE raid_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    raid_item_id BIGINT NOT NULL,
    target_type VARCHAR(20) NOT NULL,
    target_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_raid_link_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_raid_link_item FOREIGN KEY (raid_item_id) REFERENCES raid_items (id) ON DELETE CASCADE,
    -- 같은 대상을 두 번 연결하는 것은 의미가 없다.
    CONSTRAINT uq_raid_link UNIQUE (raid_item_id, target_type, target_id)
);

CREATE INDEX idx_raid_link_project ON raid_links (project_id);
CREATE INDEX idx_raid_link_item ON raid_links (raid_item_id);
CREATE INDEX idx_raid_link_target ON raid_links (target_type, target_id);

-- 기존 단일 연결을 옮긴다. 값을 잃지 않고 옮기는 것이 이 마이그레이션의 요점이다.
INSERT INTO raid_links (project_id, raid_item_id, target_type, target_id, created_at)
SELECT project_id, id, 'WBS_ITEM', wbs_item_id, created_at
  FROM raid_items
 WHERE wbs_item_id IS NOT NULL;

-- 옛 컬럼은 지운다. 두 곳에 같은 사실을 두면 곧 서로 어긋난다.
ALTER TABLE raid_items DROP CONSTRAINT fk_raid_wbs_item;
DROP INDEX idx_raid_wbs_item;
ALTER TABLE raid_items DROP COLUMN wbs_item_id;
