-- 프로젝트 커밋 히스토리 (docs/tasks/commit-history.md).
--
-- git 커밋과 같은 감각으로, 사람이 명시적으로 찍는 "그 순간의 박제". export(ExportService)와
-- 반대로 판정값까지 포함한 화면 응답 모음(computed_payload)을 그대로 저장한다 — 계산 로직이
-- 나중에 바뀌어도 과거에 실제로 보고했던 숫자가 따라 바뀌면 안 되기 때문이다(§2.1). 선례는
-- progress_snapshots(V19)의 metrics 컬럼과 같은 태도다.
--
-- 압축하지 않는다(§2.3) — DB에서 내용을 직접 확인할 수 있어야 한다. 그래서 TEXT 두 컬럼을 그대로
-- 둔다. CLOB은 쓰지 않는다: PostgreSQL에는 CLOB 타입이 없고, TEXT는 H2에서
-- CHARACTER LARGE OBJECT의 별칭으로 받아들여져 양쪽에서 그대로 돈다.
CREATE TABLE project_commits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    -- MAX(version)+1로 채번한다(서비스 코드). 삭제된 번호는 재사용하지 않는다 — count+1을 쓰면
    -- 중간 버전을 지운 뒤 다음 커밋이 지운 버전과 같은 수로 채번되어 UNIQUE 제약에 걸린다.
    version INT NOT NULL,
    -- 이 커밋의 모든 판정값(지연·위반·float·노출도·기한 초과 등)이 기준으로 삼은 날짜. 서버가
    -- 커밋 시작 시점에 한 번만 정해, 이 커밋이 호출하는 모든 조회에 같은 값을 넘긴다.
    as_of DATE NOT NULL,
    committed_at TIMESTAMP NOT NULL,
    -- 로그인이 없으므로 자유 입력 텍스트다 (baselines.approved_by와 같은 한계). 커밋 자체는 익명
    -- 저장도 허용한다 — 개인 데스크톱 사용에서 작성자를 강제할 근거가 없다.
    committed_by VARCHAR(100),
    message VARCHAR(1000),
    -- 화면에 필드가 추가되면 옛 커밋에는 그 값이 없다. 화면이 "구형 커밋"임을 말할 수 있어야 한다.
    -- ExportService.FORMAT_VERSION과 같은 값을 쓴다(커밋 시점의).
    format_version INT NOT NULL,
    -- 용량 집계용. 매번 LENGTH()로 TEXT 두 컬럼을 훑지 않기 위해 저장해 둔다(raw+computed 바이트 합).
    payload_bytes BIGINT NOT NULL,
    -- 저장된 상태만(ExportService 응답 그대로). 복원(새 프로젝트 생성)에 쓴다.
    raw_payload TEXT NOT NULL,
    -- 판정값까지 포함한 화면 응답 모음(WBS·간트·RACI·RAID·Backlog·Sprint·진척·대시보드). 시점
    -- 조회에 쓴다. 계산 로직이 바뀌어도 이 값은 불변이다.
    computed_payload TEXT NOT NULL,

    CONSTRAINT fk_commit_project FOREIGN KEY (project_id)
        REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT uq_commit_version UNIQUE (project_id, version)
);

CREATE INDEX idx_commit_project ON project_commits (project_id);
