-- 업무 분야 Tag (docs/tasks/wbs-tree-improvements.md D-1).
--
-- 프로젝트별 태그 목록 + WBS 항목에 복수 연결. project_members 와 같은 패턴이다 — 프로젝트
-- 스코프이고 이름이 프로젝트 안에서 유일하다. 자유 문자열로 두면 Web/web/WEB 이 섞여 필터가
-- 깨지고, 한 업무가 두 분야에 걸치는 것이 정상이라 단일 분류 컬럼으로도 두지 않는다.
CREATE TABLE wbs_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    -- 선택. 비어 있으면 화면이 이름 해시로 정한다(랜덤이면 다시 그릴 때마다 바뀐다).
    color VARCHAR(20),
    sort_order INT NOT NULL,
    CONSTRAINT fk_wbs_tag_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    -- 같은 프로젝트 안에서 이름이 겹치면 칩을 구분할 수 없다.
    CONSTRAINT uq_wbs_tag_name UNIQUE (project_id, name)
);

CREATE INDEX idx_wbs_tag_project ON wbs_tags (project_id);

-- 연결은 양쪽 다 CASCADE — WBS 항목이나 태그가 사라지면 연결만 사라진다. RAID 링크와 달리
-- 여기서는 남길 기록이 없다(태그는 그 자체로 이력이 아니다).
CREATE TABLE wbs_item_tags (
    wbs_item_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    PRIMARY KEY (wbs_item_id, tag_id),
    CONSTRAINT fk_wbs_item_tag_item FOREIGN KEY (wbs_item_id) REFERENCES wbs_items (id) ON DELETE CASCADE,
    CONSTRAINT fk_wbs_item_tag_tag  FOREIGN KEY (tag_id) REFERENCES wbs_tags (id) ON DELETE CASCADE
);

CREATE INDEX idx_wbs_item_tag_tag ON wbs_item_tags (tag_id);
