CREATE TABLE wbs_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    parent_id BIGINT,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    start_date DATE,
    end_date DATE,
    progress INT NOT NULL DEFAULT 0,
    sort_order INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_wbs_items_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_wbs_items_parent FOREIGN KEY (parent_id) REFERENCES wbs_items (id) ON DELETE CASCADE,
    CONSTRAINT ck_wbs_items_progress CHECK (progress BETWEEN 0 AND 100)
);

CREATE INDEX idx_wbs_items_project ON wbs_items (project_id);
CREATE INDEX idx_wbs_items_parent ON wbs_items (parent_id);
