-- 선후행 관계 (요구사항 6.2). 현재는 FS(Finish-to-Start)만 지원하므로 관계 종류 컬럼을 두지 않고,
-- 선행 종료일 + lag_days 다음 날부터 후행이 시작될 수 있다는 규칙으로 해석합니다.
CREATE TABLE wbs_dependencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    predecessor_id BIGINT NOT NULL,
    successor_id BIGINT NOT NULL,
    lag_days INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_wbs_dep_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_wbs_dep_predecessor FOREIGN KEY (predecessor_id) REFERENCES wbs_items (id) ON DELETE CASCADE,
    CONSTRAINT fk_wbs_dep_successor FOREIGN KEY (successor_id) REFERENCES wbs_items (id) ON DELETE CASCADE,
    CONSTRAINT uq_wbs_dep_pair UNIQUE (predecessor_id, successor_id),
    CONSTRAINT ck_wbs_dep_not_self CHECK (predecessor_id <> successor_id)
);

CREATE INDEX idx_wbs_dep_project ON wbs_dependencies (project_id);
