-- 프로젝트 구성원 (요구사항 4.2). RACI 매트릭스의 열이 되므로 RACI보다 먼저 필요하다.
CREATE TABLE project_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255),
    position VARCHAR(100),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_project_members_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    -- 같은 프로젝트 안에서 이름이 겹치면 매트릭스 열을 구분할 수 없다.
    CONSTRAINT uq_project_members_name UNIQUE (project_id, name)
);

CREATE INDEX idx_project_members_project ON project_members (project_id);
