-- RACI 배정 (요구사항 7.1). 한 칸(업무 × 구성원)에 여러 글자가 올 수 있도록
-- (wbs_item_id, member_id, raci_role)로 유일성을 잡는다. 담당자가 책임자를 겸하는
-- 흔한 경우를 한 글자로 제한하면 7.4(Responsible 누락) 검증이 잘못 걸린다.
CREATE TABLE raci_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    wbs_item_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    raci_role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_raci_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_raci_wbs_item FOREIGN KEY (wbs_item_id) REFERENCES wbs_items (id) ON DELETE CASCADE,
    CONSTRAINT fk_raci_member FOREIGN KEY (member_id) REFERENCES project_members (id) ON DELETE CASCADE,
    CONSTRAINT uq_raci_cell_role UNIQUE (wbs_item_id, member_id, raci_role)
);

CREATE INDEX idx_raci_project ON raci_assignments (project_id);
CREATE INDEX idx_raci_wbs_item ON raci_assignments (wbs_item_id);
