-- RAID 로그 (요구사항 9). 네 종류(Risk/Assumption/Issue/Dependency)가 제목·상태·소유자·기한 등
-- 대부분의 필드를 공유하고 한 화면에서 함께 읽히므로, 종류별 테이블 대신 raid_type 구분 컬럼을
-- 둔 한 테이블로 둔다. 종류별 테이블은 CRUD를 네 벌로 늘리면서 얻는 것이 없다.
CREATE TABLE raid_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    raid_type VARCHAR(20) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    status VARCHAR(20) NOT NULL,
    -- 확률·영향은 둘 다 있을 때만 노출도(exposure)로 환산된다. 위험이 대표적인 사용처지만
    -- 종류로 제한하지 않는다 — 이미 발생한 이슈에 영향만 적는 것도 정상적인 사용이다.
    probability VARCHAR(20),
    impact VARCHAR(20),
    -- 소유자는 프로젝트 구성원(요구사항 4.2)을 가리킨다. 구성원이 빠지면 항목은 남고
    -- 소유자만 비워야 하므로 SET NULL 이다 (CASCADE 면 기록이 사라진다).
    owner_member_id BIGINT,
    due_date DATE,
    response VARCHAR(2000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_raid_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_raid_owner FOREIGN KEY (owner_member_id) REFERENCES project_members (id) ON DELETE SET NULL
);

CREATE INDEX idx_raid_project ON raid_items (project_id);
