-- 실행 방식 변경 이력 (Hybrid PM Step 2 지시서 7항).
--
-- 저장소에는 변경 이력 기능이 아직 없다(요구사항 8.2도 미구현). 그래서 이 변경에 필요한 최소
-- 범위만 둔다 — 설계 §11.1의 일반 ChangeLog는 Step 5에서 가중치·Baseline 이력과 함께 도입하고
-- 이 표를 그때 흡수한다. 지금 일반 이력 테이블을 만들면 Step 5의 기능을 선행 구현하는 셈이 된다.
--
-- 변경자·사유 컬럼은 두지 않는다. 로그인이 없어 변경자를 알 수 없고, 사유를 받을 화면도 없는
-- 상태에서 컬럼만 만들면 아무도 채우지 않는 값이 남는다. 둘 다 계정 개념과 함께 와야 한다.
CREATE TABLE wbs_execution_mode_changes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    wbs_item_id BIGINT NOT NULL,
    -- 미지정(NULL) → 지정, 지정 → 미지정도 이력이므로 양쪽 모두 NULL을 허용한다.
    previous_mode VARCHAR(20),
    new_mode VARCHAR(20),
    changed_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_wbs_mode_change_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    -- 항목이 지워지면 그 항목의 실행 방식 이력은 가리킬 대상이 없어 표시할 곳도 없다.
    -- 오래 남아야 하는 보고 이력은 Step 5의 ChangeLog(대상을 FK 없이 기록) 몫이다.
    CONSTRAINT fk_wbs_mode_change_item FOREIGN KEY (wbs_item_id) REFERENCES wbs_items (id) ON DELETE CASCADE
);

CREATE INDEX idx_wbs_mode_change_project ON wbs_execution_mode_changes (project_id);
CREATE INDEX idx_wbs_mode_change_item ON wbs_execution_mode_changes (wbs_item_id);
